### ISSUE TITLE
如何在historyApiFallback中使用regular express

### ISSUE THREAD

**Issue by LiangZugeng** [nowa-webpack/nowa-server#17]
目前我们在使用nowa server做开发，React-Router使用了browserHistory，所以需要配置nowa server支持history fallback，目前我们的dist目录中静态文件和目录的结构如下：
/
|--images
|--scripts
|--app.cs
|--app.js
|--index.html

以下url只在客户端做路由，并不会向服务端请求数据，这些url就是要fallback到index.html的url，以便在客户端刷新时能得到SPA的index.html：
/login
/categories
/categories/create
/categories/edit/:id
/products
/products/create
/products/edit/:id
...

我们修改了abc.json，使用historyApiFallback选项添加这些URL，目前abc.json中historyApiFallback的设置如下：
"historyApiFallback": {
            "/login": "/index.html",
            "/categories": "/index.html",
            "/products": "/index.html"
        }

这里的一个问题就是：每当客户端使用的路由URL多出来一个时（比如增加了/customers），我们就需要修改abc.json并添加相应的匹配项，非常麻烦。

目前我们的想法是利用historyApiFallback指定一个regular express，把dist目录中所有静态文件和固定目录（images/scripts）排除，其他所有URL都Fallback到index.html。我尝试了两个小时，没能成功，看了nowa server的源码，发现添加historyApiFallback时代码的rule应该是字符串，app.use不能把字符串作为regular expression使用，所以失败了，不知道我们理解是否正确？

`
      // history api fallback rewrites
      if (historyApiFallback) {
        for (let rule in historyApiFallback) {
          app.use(rule, function(req, res, next) {
            var url = historyApiFallback[rule];
            if (req.params && url.indexOf('{{') !== -1) {
              url = url.replace(/\{\{([^}]+)\}\}/g, function(p, p1) {
                return req.params[p1] || '';
              });
            }
            req._parsedUrl.pathname = url;
            next();
          });
        }
      }`

请教在我们的场景和要求中如何配置nowa server来实现我们的需求。

**Comment by gbk** [comment]
你直接在根目录下加正则也不好维护吧？
能否在前面加一级路径？这样看起来更整洁，也可以满足你的需求了：
```json
{
  "options": {
    "historyApiFallback": {
      "/pages/*": "/index.html"
    }
  }
}
```

**Comment by LiangZugeng** [comment]
我找个时间尝试把app的所有导航路径全部替换掉测试一下你的建议，这里面涉及到所有导航的跳转要修改，有点工作量，不过还是谢谢了。这个问题先关了吧。
