### ISSUE TITLE
需要把scan后的新的port暴露出来

### ISSUE THREAD

**Issue by Jirapo** [nowa-webpack/nowa-server#18]

**Comment by gbk** [comment]
![image](https://cloud.githubusercontent.com/assets/865717/23749089/72883b8a-0501-11e7-8025-1ca5bc7addcf.png)

启动时候增加环境变量 `NOWA_UID`，进程相关信息会写入 `${os.tmpdir()}/nowa-server-${NOWA_UID}`，JSON 格式：
```json
{
  "uid": "abc",
  "address": "http://192.168.1.1:3000"
}
```

**Comment by gbk** [comment]
改成 `${os.tmpdir()}/nowa-server-${NOWA_UID}.json`
